### ISSUE TITLE
it looks like we are loosing significant signal strength if the config option "sampling_rate" is set to 1000000Hz 

### ISSUE THREAD

**Issue by lampep** [trackIT-Systems/tsOS-vhf#7]

**Comment by jonashoechst** [comment]
This effect is likely due to the reduced time per sample in which the voltage at the ADC is built. The effect is also known from microphones which appear to have less gain when sampled with a higher sampling rate. 

There is no fix except using other hardware, i.e. adding an amplifier. However a systematic study should be conducted to find the limits of usable configurations.
